config/routes.rb
Mybook::Application.routes.draw do

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'register', to: 'devise/registrations#new', as: :register
  end

  get 'my_wall', to: 'my_wall#show', as: :my_wall

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :wallposts
  get 'wall', to: "wallposts#index", as: :wall

  root :to => "wallposts#index"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  validates :first_name, presence: true

  validates :last_name, presence: true
  
  validates :profile_name, presence: true,
  						 uniqueness: true,
  						 format: { with: /\A[a-zA-Z\-\_]+\Z/, 
                      message: "should have no spaces" }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :wallposts

  attr_accessible :first_name, :last_name, :profile_name, :email, :password, :password_confirmation
 
  def full_name
  	first_name + " " + last_name
  end

  def gravatar_url
    email_stripped = email.strip
    email_downcased = email_stripped.downcase
    hash = Digest::MD5.hexdigest(email_downcased)

    "http://gravatar.com/avatar/#{hash}"

  end
end

app/models/wallpost.rb
class Wallpost < ActiveRecord::Base
	attr_accessible :content, :user_id
	belongs_to :user

	validates :content, presence: true,
    				   length: { minimum: 10, maximum: 1000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_filter :configure_permitted_parameters, if: :devise_controller?

    protect_from_forgery with: :exception

    protected

    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, 
                                                                                          :email, :password, :password_confirmation) }
    end
end

app/controllers/my_wall_controller.rb
class MyWallController < ApplicationController
  def show
  	@user = current_user
  	if @user
  		@myposts = @user.wallposts.all.reverse
  		render action: :show
  	else
  		redirect_to login_path
  	end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :current_password)
  end
  private :sign_up_params
  private :account_update_params
end

app/controllers/wallposts_controller.rb
class WallpostsController < ApplicationController
  before_action :set_wallpost, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new]
  # GET /wallposts
  # GET /wallposts.json
  def index
    @wallposts = Wallpost.all.reverse
  end

  # GET /wallposts/1
  # GET /wallposts/1.json
  def show
  end

  # GET /wallposts/new
  def new
    @wallpost = Wallpost.new
  end

  # GET /wallposts/1/edit
  def edit
  end

  # POST /wallposts
  # POST /wallposts.json
  def create
    @wallpost = current_user.wallposts.new(wallpost_params)

    respond_to do |format|
      if @wallpost.save
        format.html { redirect_to @wallpost, notice: 'Wallpost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wallpost }
      else
        format.html { render action: 'new' }
        format.json { render json: @wallpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallposts/1
  # PATCH/PUT /wallposts/1.json
  def update
    respond_to do |format|
      if @wallpost.update(wallpost_params)
        format.html { redirect_to @wallpost, notice: 'Wallpost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wallpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallposts/1
  # DELETE /wallposts/1.json
  def destroy
    @wallpost.destroy
    respond_to do |format|
      format.html { redirect_to wallposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallpost
      @wallpost = Wallpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallpost_params
      params.require(:wallpost).permit(:name, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :notice
			"alert-success"
		when :alert
			"alert-error"
		else
			""
		end
	end
end

app/helpers/my_wall_helper.rb
module MyWallHelper
end

app/helpers/wallposts_helper.rb
module WallpostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallposts</title> 
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

</head>

<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href="/wall">The Wall</a>
				<ul class="nav">
					<li><%= link_to "My Wall", my_wall_path %></li>
					<li><%= link_to "Build Wall", new_wallpost_path %></li>
				</ul>
				<% if user_signed_in? %>
					<ul class="nav pull-right">
						<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
						<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
					</ul>
				<% else %>
					<ul class="nav pull-right">
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					</ul>
				<% end %>
			</div>
		</div>
	</div>

	<div class="container">
		<% flash.each do |type, message| %>
		<div class="alert <%= flash_class type%>">
  			<button type="button" class="close" data-dismiss="alert">&times;</button>
  			<%= message %>
  		</div>
		<% end %>

		<%= yield %>
	</div>
	
</body>
</html>

app/views/my_wall/show.html.erb
<div class="page-header">
	<div class="row">
  		<div class="span2">
        	<%= image_tag current_user.gravatar_url %>
		</div>
		<div class="span4">
			<h1><%= @user.full_name %></h1>
		</div>
	</div>
</div>


<% @myposts.each do |post| %>
<div class="mini-layout">
    <div class="mini-layout-body">
		<p><%= post.content %></p><br />
		<%= link_to time_ago_in_words(post.created_at) + " ago", post %>
		 <span class="admin">
         | <%= link_to "Edit", edit_wallpost_path(post) %>
         | <%= link_to "Delete", post,  method: :delete, data: { confirm: "Are you sure?" } %></span>
	</div>
</div>
<% end %>

app/views/wallposts/_form.html.erb
<%= simple_form_for(@wallpost, html: {class: "form-horizontal"}) do |f| %>
  <% if @wallpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallpost.errors.count, "error") %> prohibited this wallpost from being saved:</h2>

      <ul>
      <% @wallpost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :content %><br />
    <%= f.button :submit, class: "btn btn-success" %><br /><br />
    <%= link_to 'Back', wallposts_path, class: "btn btn-primary" %>
<% end %>
 
   

app/views/wallposts/edit.html.erb
<h1>Changes</h1>

<%= render 'form' %>

app/views/wallposts/index.html.erb
<div class="page-header">
  <h1>Wall</h1>
</div>


<% @wallposts.each do |wallpost| %>
  <div class="mini-layout">
    <div class="row">
      <div class="span1">
     <%=link_to image_tag(wallpost.user.gravatar_url), wallpost %>
      </div>
      <div class="span10">
        <div class="mini-layout-body">
          <strong><%= wallpost.user.profile_name %></strong>
          <p><%= wallpost.content %></p>
            <div class="meta"> 
              <%= link_to time_ago_in_words(wallpost.created_at) + " ago", wallpost %> 
                <span class="admin">
                  <% if user_signed_in? && current_user.first_name == "keerthi" %>
                     | <%= link_to "Delete", wallpost,  method: :delete, data: { confirm: "Are you sure?" } %>
                 <% else %>
                  <% end %>
                </span>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/wallposts/new.html.erb
<h1>Build Wall</h1>

<%= render 'form' %>

app/views/wallposts/show.html.erb
<div class="layout">
<div class="row">
  	<div class="span1">
        <%= image_tag @wallpost.user.gravatar_url %>
	</div>
	<div class="span4">
		<h3><%= @wallpost.user.full_name %></h3>
	</div>
</div>
<div class="span1">
</div>
	<p>
	<%= @wallpost.content %>
	</p>

<%= link_to 'Back', wallposts_path %>
</div>